# Generated by Django 3.2.6 on 2021-08-20 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statement', models.TextField()),
                ('Name', models.CharField(max_length=200)),
                ('Code', models.TextField()),
                ('Difficulty', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.CharField(max_length=200)),
                ('Output', models.CharField(max_length=200)),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Verdict', models.CharField(max_length=200)),
                ('Time_Submitted', models.DateTimeField(auto_now=True)),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
