# Generated by Django 3.2.6 on 2021-08-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210818_1908'),
        ('blog', '0002_auto_20210819_0406'),
    ]

    operations = [
    ]
